### ISSUE TITLE
Refactor start() so that it uses the same inputs as other rooms

### ISSUE THREAD

**Issue by EmbeddedMan** [davidtcalabrese/minnetonka#4]

**Comment by davidtcalabrese** [comment]
meaning change letter inputs to numbers?

**Comment by EmbeddedMan** [comment]
Exactly. If we ever (hopefully someday) move to a data driven approach to this game rather than hard coding every text string and choice in a function, we can abstract this functionality (inputting commands from the user) away into a single function/objection.
